strList00 = [
    #   "backup",
    "all-in-one",
    #   "informatica",
    "armazenamento",
    #    "notebook",
    # "endpoints",
    # "armazenamento",
    # "equipamento",
    # "infraestrutura",
]

strList = [
    "endpoints",
    "switch san",
    "anti-virus",
    "antivirus",
    "apache",
    "appliance",
    "armazenamento",
    "backup",
    "balanceador",
    "bigdata",
    "cabeamento",
    "cftv",
    "chaveador",
    "chaveadores",
    "cloudera",
    "confluent",
    "convergencia",
    "cpu",
    "director",
    "directors",
    "disco",
    "discos",
    "endpoint",
    "equipamento",
    "equipamentos",
    "fiber",
    "fibre",
    "ficon",
    "flash",
    "hardware",
    "hci",
    "hiperconvergencia",
    "informatica",
    "infraestrutura",
    "kafka",
    "nuvem",
    "nvme",
    "notebook",
    # "tablet",
    "all-in-one",
    "desktop",
    "mainframe",
    "rede",
    "servidores",
    "sockets",
    "software",
    "ssd",
    "storage",
    "storages",
    "subsistema",
    "subsistemas",
    "symantec",
    "swtich",
    "tecnologia torre",
    "torre",
]


def get_list():
    return strList
